### ISSUE TITLE
Changes to burp JSON output

### ISSUE THREAD

**Issue by grke** [ZungBang/burpfs#1]
Hello,

I thought I had better give you a few weeks notice:

For the next release of burp-1.4.x, I am planning to change the JSON output slightly, so that it can also support these commands:
burp -j -a l
burp -j -a L
burp -j -a l -b 3
burp -j -a L -b 3
burp -j -a l -b a
burp -j -a L -b a
It is already implemented on burp git master.
The output for 'burp -j -a L -b 3' now looks like this:

{
 "backups":
 [
  {
   "timestamp": "0000003 2013-11-10 20:39:49",
   "deletable": "false",
   "directory": "",
   "regex": "",
   "items":
   [
    {
     "name": "/home/graham/testdir2",
     "link": "",
     "st_dev": 2049,
     "st_ino": 4194688,
     "st_mode": 16893,
     "st_nlink": 2,
     "st_uid": 1000,
     "st_gid": 1000,
     "st_rdev": 0,
     "st_size": 4096,
     "st_atime": 1384090785,
     "st_mtime": 1384090784,
     "st_ctime": 1384090784
    },
    ...and so on.

Notice that I also removed the "type" field, because that is something that I think should stay internal to burp.
If you were using that before, you should use the st_mode field instead - the meaning of the different bits can be found in /usr/include/linux/stat.h.

The reason for the format changes is so that it can support information about multiple different backups.

**Comment by ZungBang** [comment]
Thanks for the heads up. But I'm not happy - please read on...

I am using the type field in order to detect hardlinks in the backup. Checking <code>st_mode</code> is not enough for this - without the type field I must cross-reference all <code>st_ino</code> fields for all files, only to determine which files share the same inode. And even then I can't tell which of these <code>burp</code> backed up as a file, and which it backed up as a hardlink - and this is the real problem, since <code>burp</code> cannot restore the hardlinks, without first restoring the actual files!

So, please, either put the type field back, or let me know how I can restore hardlinks without trying all filesystem entries with the same inode?

**Comment by ZungBang** [comment]
OK, I take it back - I've looked into it and I see that the "link" field points to the hardlink target, which should allow me to recognize hardlinks and find their targets without the type field.

**Comment by ZungBang** [comment]
Fix implemented in 223aeb819facd3560de70fac392bb9ecf749ea65

I have only tested that it still works with <code>burp</code> 1.3.24 (my backup server at home) - I don't have time to test this w/ 1.4.x at the moment, so I'm leaving this issue open for the time being.

**Comment by grke** [comment]
OK, cool. Thanks for the quick response!

**Comment by grke** [comment]
I guess this is all OK, since it was more than a year ago - closing.

**Comment by grke** [comment]
Ah, whoops, I made a mistake - I thought this was in the burp issue list.
If you need it to be open, please do open it again.
